"""empty message.

Revision ID: 42dced9a9a25
Revises: ad4e854a4b93
Create Date: 2024-06-05 18:31:34.660112
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "42dced9a9a25"
down_revision = "ad4e854a4b93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("title_of_courtesy", sa.String(length=64), nullable=True),
        sa.Column("birthdate", sa.String(length=64), nullable=False),
        sa.Column("hire_date", sa.DateTime(), nullable=False),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("postal_code", sa.String(length=64), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.Column("home_phone", sa.String(length=64), nullable=False),
        sa.Column("extension", sa.String(length=64), nullable=True),
        sa.Column("photo", sa.LargeBinary(), nullable=True),
        sa.Column("notes", sa.String(length=64), nullable=True),
        sa.Column("reports_to", sa.Integer(), nullable=True),
        sa.Column("photo_path", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["reports_to"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employees")
    # ### end Alembic commands ###
