"""empty message.

Revision ID: 958a22329222
Revises: e3049f0f41ef
Create Date: 2024-06-06 12:00:18.237472
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "958a22329222"
down_revision = "e3049f0f41ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("order_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("order_id", sa.VARCHAR(length=64), nullable=False)
        )

    # ### end Alembic commands ###
