"""empty message.

Revision ID: c27a2e221a35
Revises: d5d79f067f12
Create Date: 2024-06-06 11:11:25.164318
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c27a2e221a35"
down_revision = "d5d79f067f12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("customer_id", sa.String(length=64), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_column("customer_id")

    # ### end Alembic commands ###
