"""empty message.

Revision ID: e3049f0f41ef
Revises: 56a3f2296499
Create Date: 2024-06-06 11:51:32.724512
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3049f0f41ef"
down_revision = "56a3f2296499"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shippers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_name", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("order_date", sa.DateTime(), nullable=False),
        sa.Column("required_date", sa.DateTime(), nullable=False),
        sa.Column("shipped_date", sa.DateTime(), nullable=True),
        sa.Column("freight", sa.Integer(), nullable=True),
        sa.Column("ship_name", sa.String(length=64), nullable=False),
        sa.Column("ship_address", sa.String(length=64), nullable=False),
        sa.Column("ship_city", sa.String(length=64), nullable=False),
        sa.Column("ship_region", sa.String(length=64), nullable=False),
        sa.Column("ship_postal_code", sa.String(length=64), nullable=False),
        sa.Column("ship_country", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("ship_via", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_via"],
            ["shippers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customers_customer_id"), ["customer_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customers_customer_id"))

    op.drop_table("orders")
    op.drop_table("shippers")
    # ### end Alembic commands ###
